spring:
  application:
    name: api-gateway

server:
  port: 8101

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
