spring:
  application:
    name: api-gateway

server:
  port: 8101

zuul:
  routes:
#  single-instance
    api-a:
      path: /api-a/**
      url: http://localhost:9001/
#  multi-instance
    api-b:
      path: /api-b/**
      serviceId: api-b

api-b:
  ribbon:
    listOfServers: http://localhost:9001/, http://localhost:9002/
